### ISSUE TITLE
Floating bug while scheduling or restructuring

### ISSUE THREAD

**Issue by Resurrectiontent** [Industrial-AI-Research-Lab/sampo#4]
Sometimes scheduling fails, and failure may appear in different places. Mostly scheduling fails on:
```
wg = graph_restructuring(wg, use_lag_edge_optimization=True)
```
with the following error message:
```
KeyError: '78849da5-7790-4dca-bf61-eb991f4fadc6'
```
![image](https://user-images.githubusercontent.com/52248014/217565876-f4f6e86c-7688-4aac-8ba2-a8039b8c05ac.png)

Less frequently problem appears on:
```
schedule = GeneticScheduler().schedule(wg, contractors)
```
with error
```
ValueError: min() arg is an empty sequence
```
![image](https://user-images.githubusercontent.com/52248014/217566164-ede76232-3c95-4fab-9509-5cdba489082f.png)

**Comment by StannisMod** [comment]
The problem with is not a problem with `sampo`. I added input validation to `Scheduler#schedule` in [this commit](https://github.com/Industrial-AI-Research-Lab/sampo/pull/5/commits/2c502daa3f839b4b21caee73eca9aa8d27b5dd15). It should be included by corresponding pull request.

**Comment by StannisMod** [comment]
Problem with graph restructuring is in-work.

**Comment by StannisMod** [comment]
Issue performed because of bad input data.
Resolved on client side.
